blank_issues_enabled: true
contact_links:
  - name: Microsoft ADK documentation
    url: https://learn.microsoft.com/windows-hardware/get-started/adk-install
    about: Install Microsoft's Windows ADK and WinPE add-on.
